[profile.default]
# solc_version = "0.8.13"

src = 'src'
out = 'out'
libs = ['lib']

optimizer = true
optimizer_runs = 20000

# gas_reports = ["Task"]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config